Lock lodash at 4.13.1
We're currently seeing a bug with how the latest version of lodash is
interacting weirdly with jest:

TypeError: lodash.assign is not a function
    at Object.ModuleResolver (node_modules/eslint/lib/util/module-resolver.js:42:27)
    at Object.<anonymous> (node_modules/eslint/lib/config/config-file.js:60:16)
    at Runtime._execModule (node_modules/jest-runtime/build/index.js:375:17)
    at Runtime.requireModule (node_modules/jest-runtime/build/index.js:210:14)
    at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:274:19)
    at Object.<anonymous> (node_modules/eslint/lib/config.js:14:18)
    at Runtime._execModule (node_modules/jest-runtime/build/index.js:375:17)
    at Runtime.requireModule (node_modules/jest-runtime/build/index.js:210:14)
    at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:274:19)

This error started happening in our Travis build, with no change
seemingly introducing it. I diffed outputs from two runs, one failing
[1] and one passing [2], and found that there was a difference in lodash
version between them. The passing one was using lodash 4.13.1. The
failing one was using 4.14.0.

I don't know exactly what's going on, but the old version isn't causing
any problems. I filed a bug with jest [3] in the hopes of getting some
help.

[1]: https://travis-ci.org/Galooshi/import-js/builds/147130152
[2]: https://travis-ci.org/Galooshi/import-js/builds/146905863
[3]: https://github.com/facebook/jest/issues/1319