Remove process from node core modules list
`process` is globally available in Node environments, so we shouldn't
import it. Doing so will result in an error of the following kind when
executing the code:

> Error: Cannot find module 'process' from 'Foo.js'

Fixes #236