Add Node v6.1 to travis build
With this version, tests are failing locally for me with a bunch of
failures like this:

● Importer › #fixImports › when the last import is removed from a named import › it remov
es the whole import
  - TypeError: Cannot read config file: /Users/henrictrotzig/import-js/.eslintrc.js
    Error: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.dirname (path.js:1324:5)
        at module.exports (node_modules/require-uncached/index.js:11:34)
        at loadJSConfigFile (node_modules/eslint/lib/config/config-file.js:161:16)
        at loadConfigFile (node_modules/eslint/lib/config/config-file.js:200:22)
        at Object.load (node_modules/eslint/lib/config/config-file.js:494:18)
        at loadConfig (node_modules/eslint/lib/config.js:64:33)