Add message when js/json config file can't be parsed
We want to help people better figure out why their config file isn't
working. Without try-catching and adding a message, the importing
process most likely would have failed with a cryptic message. Or if you
were using the daemon, it would probably have crashed.

The message will look something like this:
Unable to parse configuration file. Reason:
/Users/henrictrotzig/import-js/.importjs.js:5
  excludes: [
  ^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.readJsFile (/Users/henrictrotzig/import-js/build/FileUtils.js:35:12)
    at Configuration.loadUserConfig (/Users/henrictrotzig/import-js/build/Configuration.js
:232:40)
No JS module to import for `path`