Make daemon work when watchman binary is unavailable
During development, I haven't tested import-js without watchman being
installed. I asked @lencioni to give it a spin without first installing
watchman, and he reported seeing this error:

Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3

It turns out that we have to subscribe to the `error` event from the
watchman Client to catch this error.

With the changes in this commit, you are now able to run the daemon
without having watchman installed (in which case we fallback to using a
different file finding strategy).